font_family      RobotoMono Nerd Font
font_size        15.0

include ./snazzy.conf

cursor_shape     beam
cursor_blink_interval  0.5

background_opacity  0.95
macos_window_background_blur  0.5

window_padding_width  2
macos_show_window_title_in  all
macos_thicken_font  0
dynamic_background_opacity  yes

shell  zsh
confirm_os_window_close  1
cursor_trail 1

window_margin_width 0

enabled_layouts Tall, *
macos_option_as_alt yes
macos_titlebar_color background
macos_show_window_title_in all

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
term xterm-kitty
shell_integration enabled
allow_hyperlinks yes

allow_remote_control      yes
clipboard_control         write-clipboard write-primary

map cmd+d launch --location=hsplit
map cmd+r launch --location=vsplit
map cmd+w close_window
map cmd+[ previous_window
map cmd+] next_window
map cmd+t new_tab_with_cwd
map cmd+, edit_config_file

scrollback_lines              10000
wheel_scroll_multiplier       5.0
touch_scroll_multiplier       1.0

url_style                     curly
open_url_with                 default
copy_on_select                yes


editor                        vim
close_on_child_death          no

