# Snazzy Colorscheme for Kitty
# Based on https://github.com/sindresorhus/hyper-snazzy

foreground            #ebece6
background            #1e1f29
selection_foreground  #000000
selection_background  #81aec6
url_color             #0087BD
cursor                #e4e4e4
cursor_text_color     #f6f6f6

# black
color0   #000000
color8   #555555

# red
color1   #fc4346
color9   #fc4346

# green
color2   #50fb7c
color10  #50fb7c

# yellow
color3   #f0fb8c
color11  #f0fb8c

# blue
color4  #49baff
color12 #49baff

# magenta
color5   #fc4cb4
color13  #fc4cb4

# cyan
color6   #8be9fe
color14  #8be9fe

# white
color7   #ededec
color15  #ededec
